### ISSUE TITLE
After the latest update, shows "Waiting..." in the top bar.

### ISSUE THREAD

**Issue by shadowpanther** [LazeMSS/OctoPrint-TopTemp#20]
As it says in the title. I tried restarting Octoprint, refreshing the webpage, connecting the printer to get actual data, etc. Nothing updates.

<img width="141" alt="image" src="https://user-images.githubusercontent.com/675104/106599849-b1de3280-656a-11eb-910c-23909938a368.png">

**Comment by LazeMSS** [comment]
Can you try and turn on your developer console (F12 in chrome windows ) and refresh and post the output from that?

**Comment by shadowpanther** [comment]
```
Error calling onAllBound on view model TopTempViewModel : TopTempViewModel/self.onAllBound@http://raspistripes.local/static/webassets/packed_plugins.js?35f02421:31542:30
callViewModelIf@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:964:75
callViewModelsIf/<@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:958:153
Pn@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:94753
ur/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:105184
callViewModelsIf@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:958:95
callViewModels@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:957:72
bindViewModels@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1024:101
setTimeout handler*fetchSettings/<@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1026:726
c@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:28294
fireWith@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:29039
l@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:79800
o/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:82254
EventHandlerNonNull*send@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:82440
ajax@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:78223
OctoPrintClient.prototype.ajax@http://raspistripes.local/static/webassets/packed_client.js?8f609640:7:170
OctoPrintClient.prototype.get@http://raspistripes.local/static/webassets/packed_client.js?8f609640:7:424
OctoPrintSettingsClient.prototype.get@http://raspistripes.local/static/webassets/packed_client.js?8f609640:57:940
SettingsViewModel/self.requestData@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:245:48
fetchSettings@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1026:358
setTimeout handler*@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1026:1479
c@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:28294
fireWith@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:29039
l@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:79800
o/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:82254
EventHandlerNonNull*send@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:82440
ajax@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:78223
OctoPrintClient.prototype.ajax@http://raspistripes.local/static/webassets/packed_client.js?8f609640:7:170
OctoPrintClient.prototype.ajaxWithData@http://raspistripes.local/static/webassets/packed_client.js?8f609640:7:337
OctoPrintClient.prototype.post@http://raspistripes.local/static/webassets/packed_client.js?8f609640:7:625
OctoPrintClient.prototype.postJson@http://raspistripes.local/static/webassets/packed_client.js?8f609640:7:950
OctoPrintBrowserClient.prototype.passiveLogin@http://raspistripes.local/static/webassets/packed_client.js?8f609640:38:963
LoginStateViewModel/self.requestData@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:159:148
onServerConnect@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1026:1062
@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1026:1438
c@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:28294
fireWith@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:29039
Deferred/</s[t[0]]@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:30940
DataUpdater/self._onConnectMessage@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:838:434
OctoPrintSocketClient.prototype.propagateMessage/<@http://raspistripes.local/static/webassets/packed_client.js?8f609640:14:116
Pn@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:94753
ur/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:105184
OctoPrintSocketClient.prototype.propagateMessage@http://raspistripes.local/static/webassets/packed_client.js?8f609640:14:77
onMessage/<@http://raspistripes.local/static/webassets/packed_client.js?8f609640:21:316
Zt/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:103123
_t@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:97253
Vt/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:102923
ur/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:105191
onMessage@http://raspistripes.local/static/webassets/packed_client.js?8f609640:21:278
[5]</r.prototype.dispatchEvent@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1232:5788
[14]</</w.prototype._transportMessage/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1232:16405
[14]</</w.prototype._transportMessage@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1232:16356
[3]</i.prototype.emit@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1232:4669
packed_core.js:965:37
```

Full refresh output attached:
[console-export-2021-2-2_19-7-45.txt](https://github.com/LazeMSS/OctoPrint-TopTemp/files/5912588/console-export-2021-2-2_19-7-45.txt)

**Comment by LazeMSS** [comment]
@shadowpanther are you on octoprint discord? Its hard to tell whats causing the problem - i would like a teamviewer or more info about the problem :)

**Comment by shadowpanther** [comment]
I'm not on Octoprint discord, and I'd prefer not to give anyone direct access to my computer.

I can say that my Octoprint runs on RPi3, its web interface is behind haproxy (to pass the webcam through the same port) and I'm using Firefox, if that's relevant. Before updating to v0.0.0.3, TopTemp worked, besides the black-on-black issue.

**Comment by LazeMSS** [comment]
I found the error - I forgot to test in Firefox :(

**Comment by LazeMSS** [comment]
Fixed now :)

**Comment by LazeMSS** [comment]
@shadowpanther please try and force an update using the advanced under "Octoprint -> Software update" in settings and report back.

**Comment by shadowpanther** [comment]
Updated to 0.0.0.4, still shows "waiting"

<img width="271" alt="image" src="https://user-images.githubusercontent.com/675104/106633735-24153e00-6590-11eb-8a18-8c91ce06c61e.png">
The error message seems to be the same:

```
Error calling onAllBound on view model TopTempViewModel : TopTempViewModel/self.onAllBound@http://raspistripes.local/static/webassets/packed_plugins.js?264d5a07:31549:30
callViewModelIf@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:964:75
callViewModelsIf/<@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:958:153
Pn@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:94753
ur/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:105184
callViewModelsIf@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:958:95
callViewModels@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:957:72
bindViewModels@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1024:101
setTimeout handler*fetchSettings/<@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1026:726
c@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:28294
fireWith@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:29039
l@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:79800
o/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:82254
EventHandlerNonNull*send@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:82440
ajax@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:78223
OctoPrintClient.prototype.ajax@http://raspistripes.local/static/webassets/packed_client.js?8f609640:7:170
OctoPrintClient.prototype.get@http://raspistripes.local/static/webassets/packed_client.js?8f609640:7:424
OctoPrintSettingsClient.prototype.get@http://raspistripes.local/static/webassets/packed_client.js?8f609640:57:940
SettingsViewModel/self.requestData@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:245:48
fetchSettings@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1026:358
setTimeout handler*@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1026:1479
c@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:28294
fireWith@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:29039
l@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:79800
o/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:82254
EventHandlerNonNull*send@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:82440
ajax@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:78223
OctoPrintClient.prototype.ajax@http://raspistripes.local/static/webassets/packed_client.js?8f609640:7:170
OctoPrintClient.prototype.ajaxWithData@http://raspistripes.local/static/webassets/packed_client.js?8f609640:7:337
OctoPrintClient.prototype.post@http://raspistripes.local/static/webassets/packed_client.js?8f609640:7:625
OctoPrintClient.prototype.postJson@http://raspistripes.local/static/webassets/packed_client.js?8f609640:7:950
OctoPrintBrowserClient.prototype.passiveLogin@http://raspistripes.local/static/webassets/packed_client.js?8f609640:38:963
LoginStateViewModel/self.requestData@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:159:148
onServerConnect@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1026:1062
@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1026:1438
c@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:28294
fireWith@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:29039
Deferred/</s[t[0]]@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:30940
DataUpdater/self._onConnectMessage@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:838:434
OctoPrintSocketClient.prototype.propagateMessage/<@http://raspistripes.local/static/webassets/packed_client.js?8f609640:14:116
Pn@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:94753
ur/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:105184
OctoPrintSocketClient.prototype.propagateMessage@http://raspistripes.local/static/webassets/packed_client.js?8f609640:14:77
onMessage/<@http://raspistripes.local/static/webassets/packed_client.js?8f609640:21:316
Zt/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:103123
_t@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:97253
Vt/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:102923
ur/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:105191
onMessage@http://raspistripes.local/static/webassets/packed_client.js?8f609640:21:278
[5]</r.prototype.dispatchEvent@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1232:5788
[14]</</w.prototype._transportMessage/<@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1232:16405
[14]</</w.prototype._transportMessage@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1232:16356
[3]</i.prototype.emit@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1232:4669
packed_core.js:965:37
    callViewModelIf http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:965
    callViewModelsIf http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:958
    Pn http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    ur http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    callViewModelsIf http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:958
    callViewModels http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:957
    bindViewModels http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1024
    (Async: setTimeout handler)
    fetchSettings http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1026
    c http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    fireWith http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    l http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    o http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    (Async: EventHandlerNonNull)
    send http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    ajax http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    ajax http://raspistripes.local/static/webassets/packed_client.js?8f609640:7
    get http://raspistripes.local/static/webassets/packed_client.js?8f609640:7
    get http://raspistripes.local/static/webassets/packed_client.js?8f609640:57
    requestData http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:245
    fetchSettings http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1026
    (Async: setTimeout handler)
    <anonymous> http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1026
    c http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    fireWith http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    l http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    o http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    (Async: EventHandlerNonNull)
    send http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    ajax http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    ajax http://raspistripes.local/static/webassets/packed_client.js?8f609640:7
    ajaxWithData http://raspistripes.local/static/webassets/packed_client.js?8f609640:7
    post http://raspistripes.local/static/webassets/packed_client.js?8f609640:7
    postJson http://raspistripes.local/static/webassets/packed_client.js?8f609640:7
    passiveLogin http://raspistripes.local/static/webassets/packed_client.js?8f609640:38
    requestData http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:159
    onServerConnect http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1026
    <anonymous> http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1026
    c http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    fireWith http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    t[0] http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    _onConnectMessage http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:838
    propagateMessage http://raspistripes.local/static/webassets/packed_client.js?8f609640:14
    Pn http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    ur http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    propagateMessage http://raspistripes.local/static/webassets/packed_client.js?8f609640:14
    onMessage http://raspistripes.local/static/webassets/packed_client.js?8f609640:21
    Zt http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    _t http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    Vt http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    ur http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1
    onMessage http://raspistripes.local/static/webassets/packed_client.js?8f609640:21
    dispatchEvent http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1232
    _transportMessage http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1232
    _transportMessage http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1232
    emit http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1232
```

**Comment by LazeMSS** [comment]
Try a force refresh (CTRL+F5) and did you restart octoprint?

**Comment by shadowpanther** [comment]
Yes, Octoprint restarts itself for plugin updates, and I tried force-reloading(Cmd-Shift-R). I even tried to clear the cache.

**Comment by LazeMSS** [comment]
Strange - I have no problems on Windows 10 with edge, chrome or firefox - have you tried deleting your toptemp settings (eraser icon in plugin manager)- there should be no problems migrating settings but maybe there is.

**Comment by shadowpanther** [comment]
Just tried in Chrome - same result, even looks like the same error. Tried fully removing the plugin and settings and reinstalling it - same. Tried in Firefox and Chrome on Windows - same. Tried setting logging for toptemp to debug - nothing in the log besides enumerating ways to get system temperatures.

**Comment by LazeMSS** [comment]
Wauww thats strange. But the error is 100% somewhere in the loading of the javascript.

What is on the line in the js:
Error calling onAllBound on view model TopTempViewModel : TopTempViewModel/self.onAllBound@http://raspistripes.local/static/webassets/packed_plugins.js?264d5a07:31549:30

and: 
callViewModelIf@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:964:75
callViewModelsIf/<@http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:958:153
Pn@http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:94753

**Comment by LazeMSS** [comment]
Oh and does the developer console say anything different in Chrome?

**Comment by shadowpanther** [comment]
You mean, the line number from the error? packed_core.js:965:37
`if(raiseErrors){throw exc;}else{log.error("Error calling",method,"on view model",viewModel.constructor.name,":",exc.stack||exc);}}}`

Chrome's console says:

```
Error calling onAllBound on view model TopTempViewModel : TypeError: Cannot read property 'ctAxisTitle' of undefined
    at TopTempViewModel.self.onAllBound (http://raspistripes.local/static/webassets/packed_plugins.js?264d5a07:31549:54)
    at callViewModelIf (http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:964:75)
    at http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:958:138
    at Pn (http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:94753)
    at Function.<anonymous> (http://raspistripes.local/static/webassets/packed_libs.js?ab739628:1:105184)
    at callViewModelsIf (http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:958:95)
    at callViewModels (http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:957:56)
    at bindViewModels (http://raspistripes.local/static/webassets/packed_core.js?b8ae0794:1024:87)
callViewModelIf @ packed_core.js?b8ae0794:965
```

**Comment by LazeMSS** [comment]
Great - thanks :)

**Comment by LazeMSS** [comment]
Fixed now I hope :)

**Comment by LazeMSS** [comment]
@shadowpanther  try and update and confirm :)
